### the frame config

spring.application.name: WechatStudy_PP
server.port: ${port:80}

logging:
  path: ${LOG_PATH:logs}

spring.datasource: 
 # dev
 url: jdbc:mysql://localhost:3306/xjc?useUnicode=yes&characterEncoding=UTF8&useSSL=false
 username: root
 password: isadmin
 driver-class-name: com.mysql.jdbc.Driver



spring.jpa:
  database: MYSQL
  show-sql: true
  hibernate.ddl-auto: validate
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  open-in-view: true

sms.verf.dataRange: 0123456789
sms.verf.length: 4
sms.verf.validMinute: 10

app.appid: wxb7c0ec433e433f2d
weixin.app.key: 88ABC274CC95E1D1740D9900BFD5422A
weixin.notifyUrl: http://47.96.163.204/api/pay/callBackNotifyUrl.do
weinxin.unifiedOrderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
weinxin.orderQueryUrl: https://api.mch.weixin.qq.com/pay/orderquery
weinxin.closeOrderUrl: https://api.mch.weixin.qq.com/pay/closeorder


alibaba.appid: 2017120800458810
alibaba.public.key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnWC1zADKRJsJHfDTYSvjwJxcpBglveLurtq6bDkcwnUG1VjbVOBpWksQtwYRciOvdoEOMF1YChPDyGGuBtOYXvEq5CkAgLWHrRiFUgu3DG8zd+2AbQIShgFf7oLnpiQ1heP03zG8q12jrdeWdyhWfmUvs+o6mNqrxxbpKdjyebrpbZCFufOqDyjPjLqPuKe4FsRl5/uXTK4/3doZGj2eCkhrD/tY1qZ8YANt+u/GG+X0Ql0+iyRuYtld5uDWLubJiSFqfgls62/M1xucAFD8tvysiL07cF3QZ2Gk3oUDsGbJdkjHdUQH6x2KFuuHawjylY2yG/Se02e/RRKnwUdiYQIDAQAB
alibaba.private.key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdYLXMAMpEmwkd8NNhK+PAnFykGCW94u6u2rpsORzCdQbVWNtU4GlaSxC3BhFyI692gQ4wXVgKE8PIYa4G05he8SrkKQCAtYetGIVSC7cMbzN37YBtAhKGAV/uguemJDWF4/TfMbyrXaOt15Z3KFZ+ZS+z6jqY2qvHFukp2PJ5uultkIW586oPKM+Muo+4p7gWxGXn+5dMrj/d2hkaPZ4KSGsP+1jWpnxgA23678Yb5fRCXT6LJG5i2V3m4NYu5smJIWp+CWzrb8zXG5wAUPy2/KyIvTtwXdBnYaTehQOwZsl2SMd1RAfrHYoW64drCPKVjbIb9J7TZ79FEqfBR2JhAgMBAAECggEAKErZYKiXIKd81xCQXeGJxweBZHXWO95884GGlyysI1Eo9bhxNzLZZkevuNwx3UIrqzBxfIp5fuL+jjAMCS1lZnFiZNXmjg1r9jI/9/iN3f4edEb3SXFtYqe5cuxK+KtulJ//UqF+R3WK8XgvysQmGOg5JVwDspzRvAAupAsqUWXVaMMLvr4gv7+kDRi/Sf2Z1gnoSmQM3hkHo84LWNlHN88MZtOWcdTn8ZpqOQZv2lTmGOiha3LbPg+vB8R0fpl3ynZr+eUeAUutni2mXXuZ4jIG9gtBPM4lhva1WJD5aMJM3SOsa35R5j05nrn2WkndXhx1A71I65Kxr0i4JBLRXQKBgQDUk232vWpSTHsxwze+rTrSdO24R9ilma9GxI8KSMTwr72fgBPVN3JX+wjW/5tb/q9TMypz5rf7tWyD28CQDtmiUdVRHcPWvqOpXS/Qfn4frdbIQL2ypo7zerwF5BQLrhRT2RXdbpxBHo3Odp1y1iAqu5GbYOVySL4BsuHd8jtwiwKBgQC9hreVMwl68gPmEHmkIawIpyMBOvIeBN4VJNzqARwoHIxZIqH3xK9ogoqyRSYsAXbiwnlpd9ptI+3CFTQif7biGiM37mviNd1xB9bSxHuWOvbKW7UHf4fCb6/qNQoHcCmysnGkokRmkEdLRe2MDoVW9s7lKDwoRZWgrKAFluqKQwKBgCgK0WbuDS4NfBNGm6SOSwtDvVe+KOAgz/R7qBoe1QIliImX/aRnOmG6RtMA+QneMrZwZ+nHJxcB+Lvp1B8OvQ4nbhBGlBJKfNe1VwFmImnjPBciotkZKMpSb0KI0QHWO7wDo2u/ny1hDQM8MrJkBVEnXekv2miprSjywjslmu67AoGActz90E/RNBEPKdTcVAwQPmJFRc6axHTAv+HKfYvUq765lJ/3t7kdceKD+o0MGGl+yumAOdpop/K5ewHsyefLR/b9Vz2JZtysa3+Lw8tO93qe7X9tFLFG7yFPZUtl26Ivs1yQoW2ytNJGUyl7UYHPcCg+tgWPh/y8NVfJ1/liBg8CgYEAvkRSqHNZsNszuOfxCoWnqRwjgPMKnq3pUl6nquudaNQZQbY5HzLXmJNdaZMUTX96R9uprblT0+XTPyKcEWOUtPAfIoMheMVxc4jbk3V1/ctfPze/LTlZddpJYEZ2EdZ/HB2AD+ew0JCkypyCLZ7Z6p0MT9t0UG/yYfF8I7Sd+vA=
alibaba.charset: utf-8
alibaba.notifyUrl: http://47.96.163.204/api/pay/aliPayCallBack.do
alibaba.trade.app.pay.url: https://openapi.alipay.com/gateway.do
alibaba.timeoutExpress: 90m
alibabaPay.public.key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjrEVFMOSiNJXaRNKicQuQdsREraftDA9Tua3WNZwcpeXeh8Wrt+V9JilLqSa7N7sVqwpvv8zWChgXhX/A96hEg97Oxe6GKUmzaZRNh0cZZ88vpkn5tlgL4mH/dhSr3Ip00kvM4rHq9PwuT4k7z1DpZAf1eghK8Q5BgxL88d0X07m9X96Ijd0yMkXArzD7jg+noqfbztEKoH3kPMRJC2w4ByVdweWUT2PwrlATpZZtYLmtDvUKG/sOkNAIKEMg3Rut1oKWpjyYanzDgS7Cg3awr1KPTl9rHCazk15aNYowmYtVabKwbGVToCAGK+qQ1gT3ELhkGnf3+h53fukNqRH+wIDAQAB